In [1]:
import pandas as pd

In [2]:
data = pd.read_csv("/content/gdrive/MyDrive/Colab Notebooks/nba.csv")

In [3]:
data.dropna(inplace=True)
print(data)
#inplace=True diyerek datanın bir kopyasını çıkartmadan orjinal datayı değiştirmiş oluyoruz

              Name            Team  Number Position   Age Height  Weight  \
0    Avery Bradley  Boston Celtics     0.0       PG  25.0    6-2   180.0
1      Jae Crowder  Boston Celtics    99.0       SF  25.0    6-6   235.0
3      R.J. Hunter  Boston Celtics    28.0       SG  22.0    6-5   185.0
6    Jordan Mickey  Boston Celtics    55.0       PF  21.0    6-8   235.0
7     Kelly Olynyk  Boston Celtics    41.0        C  25.0    7-0   238.0
..             ...             ...     ...      ...   ...    ...     ...
449    Rodney Hood       Utah Jazz     5.0       SG  23.0    6-8   206.0
451  Chris Johnson       Utah Jazz    23.0       SF  26.0    6-6   206.0
452     Trey Lyles       Utah Jazz    41.0       PF  20.0   6-10   234.0
453   Shelvin Mack       Utah Jazz     8.0       PG  26.0    6-3   203.0
456    Jeff Withey       Utah Jazz    24.0        C  26.0    7-0   231.0

           College     Salary
0            Texas  7730337.0
1        Marquette  6796117.0
3    Georgia State  1148640.0
6              LSU  1170960.0
7          Gonzaga  2165160.0
..             ...        ...
449           Duke  1348440.0
451         Dayton   981348.0
452       Kentucky  2239800.0
453         Butler  2433333.0
456         Kansas   947276.0

[364 rows x 9 columns]

In [4]:
data["Name"] = data["Name"].str.upper()
print(data.Name)

0      AVERY BRADLEY
1        JAE CROWDER
3        R.J. HUNTER
6      JORDAN MICKEY
7       KELLY OLYNYK
           ...
449      RODNEY HOOD
451    CHRIS JOHNSON
452       TREY LYLES
453     SHELVIN MACK
456      JEFF WITHEY
Name: Name, Length: 364, dtype: object

In [5]:
data["Name"] = data['Name'].str.lower()
print(data.Name)

0      avery bradley
1        jae crowder
3        r.j. hunter
6      jordan mickey
7       kelly olynyk
           ...
449      rodney hood
451    chris johnson
452       trey lyles
453     shelvin mack
456      jeff withey
Name: Name, Length: 364, dtype: object

In [6]:
data["index"] = data['Name'].str.find("a")   # içerisinde kaç tane "a" harfi var
print(data[["Name","index"]])

              Name  index
0    avery bradley      0
1      jae crowder      1
3      r.j. hunter     -1
6    jordan mickey      4
7     kelly olynyk     -1
..             ...    ...
449    rodney hood     -1
451  chris johnson     -1
452     trey lyles     -1
453   shelvin mack      9
456    jeff withey     -1

[364 rows x 2 columns]

In [7]:
data[data["Name"].str.contains("jordan")]
#içerisinde jordan ismi bulunan tüm kayıtları getirir

,Name,Team,Number,Position,Age,Height,Weight,College,Salary,index
6,jordan mickey,Boston Celtics,55.0,PF,21.0,6-8,235.0,LSU,1170960.0,4
98,deandre jordan,Los Angeles Clippers,6.0,C,27.0,6-11,265.0,Texas A&M,19689000.0,2
110,jordan clarkson,Los Angeles Lakers,6.0,PG,24.0,6-5,194.0,Missouri,845059.0,4
175,jordan mcrae,Cleveland Cavaliers,12.0,SG,25.0,6-5,179.0,Tennessee,111196.0,4
201,jordan hill,Indiana Pacers,27.0,C,28.0,6-10,235.0,Arizona,4000000.0,4
257,jordan adams,Memphis Grizzlies,3.0,SG,21.0,6-5,209.0,UCLA,1404600.0,4
289,jordan hamilton,New Orleans Pelicans,25.0,SG,25.0,6-7,220.0,Texas,1015421.0,4

In [8]:
data["Team"].str.replace(" ", "-")

0      Boston-Celtics
1      Boston-Celtics
3      Boston-Celtics
6      Boston-Celtics
7      Boston-Celtics
            ...
449         Utah-Jazz
451         Utah-Jazz
452         Utah-Jazz
453         Utah-Jazz
456         Utah-Jazz
Name: Team, Length: 364, dtype: object

In [9]:
data["Name"].str.replace(".","**")

0      avery bradley
1        jae crowder
3      r**j** hunter
6      jordan mickey
7       kelly olynyk
           ...
449      rodney hood
451    chris johnson
452       trey lyles
453     shelvin mack
456      jeff withey
Name: Name, Length: 364, dtype: object

In [12]:
data[['FirstName','LastName']] = data['Name'].loc[data['Name'].str.split().str.len()==2].str.split(expand=True)
data.head()

,Name,Team,Number,Position,Age,Height,Weight,College,Salary,index,FirstName,LastName
0,avery bradley,Boston Celtics,0.0,PG,25.0,6-2,180.0,Texas,7730337.0,0,avery,bradley
1,jae crowder,Boston Celtics,99.0,SF,25.0,6-6,235.0,Marquette,6796117.0,1,jae,crowder
3,r.j. hunter,Boston Celtics,28.0,SG,22.0,6-5,185.0,Georgia State,1148640.0,-1,r.j.,hunter
6,jordan mickey,Boston Celtics,55.0,PF,21.0,6-8,235.0,LSU,1170960.0,4,jordan,mickey
7,kelly olynyk,Boston Celtics,41.0,C,25.0,7-0,238.0,Gonzaga,2165160.0,-1,kelly,olynyk